class AppTranslations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'purchases': 'المشتريات',
      'sales': 'المبيعات',
      'inventory': 'المخزون',
      'production': 'الإنتاج',
      'financial_transactions': 'المعاملات المالية',
      'help': 'مساعدة',
      'settings': 'الإعدادات',
      'customers': 'العملاء',
      'notifications': 'الإشعارات',
      'change_language': 'تغيير اللغة',
      'smart_invoice': 'فاتورة إلكترونية',
      'number': 'رقم',
      'not_specified': 'غير محدد',
      'items_count': 'عدد العناصر',
      'total_weight': 'الوزن الكلي',
      'total_expenses': 'مجموع المصاريف',
      'goods_total': 'إجمالي البضائع',
      'select_all': 'تحديد الكل',
      'add_new': 'إضافة جديد',
      'delete_selected': 'حذف المحدد',
      'clear_selection': 'إلغاء التحديد',
      'supplier_ref': 'مرجع المورد',
      'article': 'المادة',
      'quantity': 'الكمية',
      'weight': 'الوزن',
      'unit_price': 'سعر القطعة',
      'total_amount': 'المبلغ الإجمالي',
      'purchase_price': 'سعر الشراء',
      'other_expenses': 'مصاريف أخرى',
      'item_cost': 'تكلفة القطعة',
      'actions': 'الإجراءات',
      'edit': 'تعديل',
      'delete': 'حذف',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'required': 'مطلوب',
      'invalid_number': 'رقم غير صحيح',
      'integer_only': 'رقم صحيح فقط',
      'expense_details':
          'تفاصيل المصاريف: المرجو إدخال المبالغ بدون رسوم الضريبة على القيمة المضافة',
      'transit': 'النقل',
      'customs': 'حق الجمرك',
      'exchange_cheque': 'شيك الصرف',
      'freight': 'الشحن',
      'other': 'أخرى',
      'exchange_rate': 'سعر الصرف',
      'confirm_delete': 'تأكيد الحذف',
      'delete_selected_items': 'هل تريد حذف العناصر المحددة',
      'delete_this_item': 'هل تريد حذف هذا العنصر؟',
      'enter_value': 'أدخل القيمة',
      'clear_value': 'مسح القيمة',
      // الترجمات الجديدة من ملفات الـ widgets
      'invoice_number': 'رقم الفاتورة',
      'client_name': 'اسم العميل',
      'invoice_date': 'تاريخ الفاتورة',
      'invoice_type': 'نوع الفاتورة',
      'local': 'محلي',
      'external': 'خارجي',
      'local_import': 'استيراد محلي',
      'external_import': 'استيراد خارجي',
      'add_new_invoice': 'إضافة فاتورة جديدة',
      'create_invoice': 'إنشاء الفاتورة',
      'invoice_date_time': 'تاريخ ووقت الفاتورة',
      'edit_date_time': 'تعديل التاريخ والوقت',
      'please_enter_client_name': 'يرجى إدخال اسم العميل',
      'please_enter_invoice_number': 'يرجى إدخال رقم الفاتورة',
      'close': 'إغلاق',
      'scroll_left': 'تمرير لليسار',
      'scroll_right': 'تمرير لليمين',
      'use_buttons_to_navigate': 'استخدم الأزرار للتنقل بين الأعمدة',
      'items': 'العناصر',
      'invoice_summary': 'ملخص الفاتورة',
      'customs_invoice_number': 'رقم الفاتورة الجمركية',
      'total_invoice': 'إجمالي الفاتورة',
      'total_weight_summary': 'إجمالي الوزن',
      'reference': 'المرجع',
      'category': 'الصنف',
      'unit_price_header': 'سعر القطعة',
      'purchase_price_header': 'سعر الشراء',
      'other_expenses_header': 'مصروفات أخرى',
      'total_header': 'الإجمالي',
      'status': 'الحالة',
      'completed': 'مكتملة',
      'pending': 'في الانتظار',
      'draft': 'مسودة',
      'view': 'عرض',
      'print': 'طباعة',
      'update_status': 'تحديث الحالة',
      'update_type': 'تحديث النوع',
      // الترجمات الجديدة من ملف purchases_screen.dart
      'search_invoice_or_client': 'بحث عن فاتورة أو عميل...',
      'advanced_filter': 'فلترة متقدمة',
      'add_invoice': 'إضافة فاتورة',
      'found_results_for_search': 'تم العثور على {count} نتيجة للبحث: "{query}"',
      'no_invoices': 'لا توجد فواتير',
      'no_local_invoices_created': 'لم يتم إنشاء أي فاتورة استيراد محلي بعد',
      'no_external_invoices_created': 'لم يتم إنشاء أي فاتورة استيراد خارجي بعد',
      'add_local_invoice': 'إضافة فاتورة محلية',
      'add_external_invoice': 'إضافة فاتورة خارجية',
      'invoice_added_successfully': 'تمت إضافة الفاتورة بنجاح',
      'error_adding_invoice': 'حدث خطأ أثناء إضافة الفاتورة',
      'invoice_updated_successfully': 'تم تحديث الفاتورة بنجاح',
      'error_updating_invoice': 'حدث خطأ أثناء تحديث الفاتورة',
      'invoice_deleted_successfully': 'تم حذف الفاتورة بنجاح',
      'error_deleting_invoice': 'حدث خطأ أثناء حذف الفاتورة',
      'invoice_status_updated_to': 'تم تحديث حالة الفاتورة إلى: {status}',
      'error_updating_invoice_status': 'حدث خطأ أثناء تحديث حالة الفاتورة',
      'invoice_type_updated_to': 'تم تحديث نوع الفاتورة إلى: {type}',
      'error_updating_invoice_type': 'حدث خطأ أثناء تحديث نوع الفاتورة',
      'print_invoice': 'طباعة الفاتورة',
      'do_you_want_to_print_invoice': 'هل تريد طباعة الفاتورة رقم {number}؟',
      'confirm_delete_invoice': 'تأكيد الحذف',
      'are_you_sure_delete_invoice': 'هل أنت متأكد من حذف هذه الفاتورة؟',
      'warning_cannot_undo': 'تحذير: لا يمكن التراجع عن هذا الإجراء',
      'error_loading_invoices': 'حدث خطأ أثناء تحميل الفواتير',
      'error_loading_invoice_details': 'حدث خطأ أثناء تحميل تفاصيل الفاتورة',
    },
    'en': {
      'purchases': 'Purchases',
      'sales': 'Sales',
      'inventory': 'Inventory',
      'production': 'Production',
      'financial_transactions': 'Financial Transactions',
      'help': 'Help',
      'settings': 'Settings',
      'customers': 'Customers',
      'notifications': 'Notifications',
      'change_language': 'Change Language',
      'smart_invoice': 'Smart Invoice',
      'number': 'Number',
      'not_specified': 'Not specified',
      'items_count': 'Items count',
      'total_weight': 'Total weight',
      'total_expenses': 'Total expenses',
      'goods_total': 'Goods total',
      'select_all': 'Select all',
      'add_new': 'Add new',
      'delete_selected': 'Delete selected',
      'clear_selection': 'Clear selection',
      'supplier_ref': 'Supplier Ref',
      'article': 'Article',
      'quantity': 'Quantity',
      'weight': 'Weight',
      'unit_price': 'Unit price',
      'total_amount': 'Total amount',
      'purchase_price': 'Purchase price',
      'other_expenses': 'Other expenses',
      'item_cost': 'Item cost',
      'actions': 'Actions',
      'edit': 'Edit',
      'delete': 'Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'required': 'Required',
      'invalid_number': 'Invalid number',
      'integer_only': 'Integer only',
      'expense_details': 'Expense details (enter amounts without VAT)',
      'transit': 'Transit',
      'customs': 'Customs',
      'exchange_cheque': 'Exchange Cheque',
      'freight': 'Freight',
      'other': 'Other',
      'exchange_rate': 'Exchange rate',
      'confirm_delete': 'Confirm delete',
      'delete_selected_items': 'Delete selected items?',
      'delete_this_item': 'Delete this item?',
      'enter_value': 'Enter value',
      'clear_value': 'Clear value',
      // New translations from widgets files
      'invoice_number': 'Invoice Number',
      'client_name': 'Client Name',
      'invoice_date': 'Invoice Date',
      'invoice_type': 'Invoice Type',
      'local': 'Local',
      'external': 'External',
      'local_import': 'Local Import',
      'external_import': 'External Import',
      'add_new_invoice': 'Add New Invoice',
      'create_invoice': 'Create Invoice',
      'invoice_date_time': 'Invoice Date & Time',
      'edit_date_time': 'Edit Date & Time',
      'please_enter_client_name': 'Please enter client name',
      'please_enter_invoice_number': 'Please enter invoice number',
      'close': 'Close',
      'scroll_left': 'Scroll Left',
      'scroll_right': 'Scroll Right',
      'use_buttons_to_navigate': 'Use buttons to navigate between columns',
      'items': 'Items',
      'invoice_summary': 'Invoice Summary',
      'customs_invoice_number': 'Customs Invoice Number',
      'total_invoice': 'Total Invoice',
      'total_weight_summary': 'Total Weight',
      'reference': 'Reference',
      'category': 'Category',
      'unit_price_header': 'Unit Price',
      'purchase_price_header': 'Purchase Price',
      'other_expenses_header': 'Other Expenses',
      'total_header': 'Total',
      'status': 'Status',
      'completed': 'Completed',
      'pending': 'Pending',
      'draft': 'Draft',
      'view': 'View',
      'print': 'Print',
      'update_status': 'Update Status',
      'update_type': 'Update Type',
      // New translations from purchases_screen.dart
      'search_invoice_or_client': 'Search for invoice or client...',
      'advanced_filter': 'Advanced Filter',
      'add_invoice': 'Add Invoice',
      'found_results_for_search': 'Found {count} results for search: "{query}"',
      'no_invoices': 'No invoices',
      'no_local_invoices_created': 'No local import invoices have been created yet',
      'no_external_invoices_created': 'No external import invoices have been created yet',
      'add_local_invoice': 'Add Local Invoice',
      'add_external_invoice': 'Add External Invoice',
      'invoice_added_successfully': 'Invoice added successfully',
      'error_adding_invoice': 'Error occurred while adding invoice',
      'invoice_updated_successfully': 'Invoice updated successfully',
      'error_updating_invoice': 'Error occurred while updating invoice',
      'invoice_deleted_successfully': 'Invoice deleted successfully',
      'error_deleting_invoice': 'Error occurred while deleting invoice',
      'invoice_status_updated_to': 'Invoice status updated to: {status}',
      'error_updating_invoice_status': 'Error occurred while updating invoice status',
      'invoice_type_updated_to': 'Invoice type updated to: {type}',
      'error_updating_invoice_type': 'Error occurred while updating invoice type',
      'print_invoice': 'Print Invoice',
      'do_you_want_to_print_invoice': 'Do you want to print invoice number {number}?',
      'confirm_delete_invoice': 'Confirm Delete',
      'are_you_sure_delete_invoice': 'Are you sure you want to delete this invoice?',
      'warning_cannot_undo': 'Warning: This action cannot be undone',
      'error_loading_invoices': 'Error occurred while loading invoices',
      'error_loading_invoice_details': 'Error occurred while loading invoice details',
    },
    'fr': {
      'purchases': 'Achats',
      'sales': 'Ventes',
      'inventory': 'Inventaire',
      'production': 'Production',
      'financial_transactions': 'Transactions financières',
      'help': 'Aide',
      'settings': 'Paramètres',
      'customers': 'Clients',
      'notifications': 'Notifications',
      'change_language': 'Changer de langue',
      'smart_invoice': 'Facture intelligente',
      'number': 'Numéro',
      'not_specified': 'Non spécifié',
      'items_count': 'Nombre d\'articles',
      'total_weight': 'Poids total',
      'total_expenses': 'Total des dépenses',
      'goods_total': 'Total marchandises',
      'select_all': 'Tout sélectionner',
      'add_new': 'Ajouter',
      'delete_selected': 'Supprimer la sélection',
      'clear_selection': 'Effacer la sélection',
      'supplier_ref': 'Réf. fournisseur',
      'article': 'Article',
      'quantity': 'Quantité',
      'weight': 'Poids',
      'unit_price': 'Prix unitaire',
      'total_amount': 'Montant total',
      'purchase_price': 'Prix d\'achat',
      'other_expenses': 'Autres frais',
      'item_cost': 'Coût de l\'article',
      'actions': 'Actions',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'required': 'Obligatoire',
      'invalid_number': 'Nombre invalide',
      'integer_only': 'Entier seulement',
      'expense_details': 'Détails des dépenses (saisir les montants hors TVA)',
      'transit': 'Transport',
      'customs': 'Droit de douane',
      'exchange_cheque': 'Chèque de change',
      'freight': 'Fret',
      'other': 'Autre',
      'exchange_rate': 'Taux de change',
      'confirm_delete': 'Confirmer la suppression',
      'delete_selected_items': 'Supprimer les éléments sélectionnés ?',
      'delete_this_item': 'Supprimer cet élément ?',
      'enter_value': 'Entrer la valeur',
      'clear_value': 'Effacer la valeur',
      // Nouvelles traductions des fichiers widgets
      'invoice_number': 'Numéro de facture',
      'client_name': 'Nom du client',
      'invoice_date': 'Date de facture',
      'invoice_type': 'Type de facture',
      'local': 'Local',
      'external': 'Externe',
      'local_import': 'Import local',
      'external_import': 'Import externe',
      'add_new_invoice': 'Ajouter une nouvelle facture',
      'create_invoice': 'Créer la facture',
      'invoice_date_time': 'Date et heure de facture',
      'edit_date_time': 'Modifier la date et l\'heure',
      'please_enter_client_name': 'Veuillez saisir le nom du client',
      'please_enter_invoice_number': 'Veuillez saisir le numéro de facture',
      'close': 'Fermer',
      'scroll_left': 'Défiler à gauche',
      'scroll_right': 'Défiler à droite',
      'use_buttons_to_navigate': 'Utilisez les boutons pour naviguer entre les colonnes',
      'items': 'Articles',
      'invoice_summary': 'Résumé de la facture',
      'customs_invoice_number': 'Numéro de facture douanière',
      'total_invoice': 'Total de la facture',
      'total_weight_summary': 'Poids total',
      'reference': 'Référence',
      'category': 'Catégorie',
      'unit_price_header': 'Prix unitaire',
      'purchase_price_header': 'Prix d\'achat',
      'other_expenses_header': 'Autres frais',
      'total_header': 'Total',
      'status': 'Statut',
      'completed': 'Terminée',
      'pending': 'En attente',
      'draft': 'Brouillon',
      'view': 'Voir',
      'print': 'Imprimer',
      'update_status': 'Mettre à jour le statut',
      'update_type': 'Mettre à jour le type',
      // Nouvelles traductions de purchases_screen.dart
      'search_invoice_or_client': 'Rechercher une facture ou un client...',
      'advanced_filter': 'Filtre avancé',
      'add_invoice': 'Ajouter une facture',
      'found_results_for_search': 'Trouvé {count} résultats pour la recherche : "{query}"',
      'no_invoices': 'Aucune facture',
      'no_local_invoices_created': 'Aucune facture d\'import local n\'a été créée',
      'no_external_invoices_created': 'Aucune facture d\'import externe n\'a été créée',
      'add_local_invoice': 'Ajouter une facture locale',
      'add_external_invoice': 'Ajouter une facture externe',
      'invoice_added_successfully': 'Facture ajoutée avec succès',
      'error_adding_invoice': 'Erreur lors de l\'ajout de la facture',
      'invoice_updated_successfully': 'Facture mise à jour avec succès',
      'error_updating_invoice': 'Erreur lors de la mise à jour de la facture',
      'invoice_deleted_successfully': 'Facture supprimée avec succès',
      'error_deleting_invoice': 'Erreur lors de la suppression de la facture',
      'invoice_status_updated_to': 'Statut de la facture mis à jour vers : {status}',
      'error_updating_invoice_status': 'Erreur lors de la mise à jour du statut de la facture',
      'invoice_type_updated_to': 'Type de facture mis à jour vers : {type}',
      'error_updating_invoice_type': 'Erreur lors de la mise à jour du type de facture',
      'print_invoice': 'Imprimer la facture',
      'do_you_want_to_print_invoice': 'Voulez-vous imprimer la facture numéro {number} ?',
      'confirm_delete_invoice': 'Confirmer la suppression',
      'are_you_sure_delete_invoice': 'Êtes-vous sûr de vouloir supprimer cette facture ?',
      'warning_cannot_undo': 'Attention : Cette action ne peut pas être annulée',
      'error_loading_invoices': 'Erreur lors du chargement des factures',
      'error_loading_invoice_details': 'Erreur lors du chargement des détails de la facture',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['ar']![key] ?? key;
  }
}
