class AppTranslations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'purchases': 'المشتريات',
      'sales': 'المبيعات',
      'inventory': 'المخزون',
      'production': 'الإنتاج',
      'financial_transactions': 'المعاملات المالية',
      'help': 'مساعدة',
      'settings': 'الإعدادات',
      'customers': 'العملاء',
      'notifications': 'الإشعارات',
      'change_language': 'تغيير اللغة',
      'smart_invoice': 'فاتورة إلكترونية',
      'number': 'رقم',
      'not_specified': 'غير محدد',
      'items_count': 'عدد العناصر',
      'total_weight': 'الوزن الكلي',
      'total_expenses': 'مجموع المصاريف',
      'goods_total': 'إجمالي البضائع',
      'select_all': 'تحديد الكل',
      'add_new': 'إضافة جديد',
      'delete_selected': 'حذف المحدد',
      'clear_selection': 'إلغاء التحديد',
      'supplier_ref': 'مرجع المورد',
      'article': 'المادة',
      'quantity': 'الكمية',
      'weight': 'الوزن',
      'unit_price': 'سعر القطعة',
      'total_amount': 'المبلغ الإجمالي',
      'purchase_price': 'سعر الشراء',
      'other_expenses': 'مصاريف أخرى',
      'item_cost': 'تكلفة القطعة',
      'actions': 'الإجراءات',
      'edit': 'تعديل',
      'delete': 'حذف',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'required': 'مطلوب',
      'invalid_number': 'رقم غير صحيح',
      'integer_only': 'رقم صحيح فقط',
      'expense_details':
          'تفاصيل المصاريف المرجو إدخال المبالغ بدون رسوم الضريبة على القيمة المضافة(',
      'transit': 'النقل',
      'customs': 'حق الجمرك',
      'exchange_cheque': 'شيك الصرف',
      'freight': 'الشحن',
      'other': 'أخرى',
      'exchange_rate': 'سعر الصرف',
      'confirm_delete': 'تأكيد الحذف',
      'delete_selected_items': 'هل تريد حذف العناصر المحددة',
      'delete_this_item': 'هل تريد حذف هذا العنصر؟',
      'enter_value': 'أدخل القيمة',
      'clear_value': 'مسح القيمة',
    },
    'en': {
      'purchases': 'Purchases',
      'sales': 'Sales',
      'inventory': 'Inventory',
      'production': 'Production',
      'financial_transactions': 'Financial Transactions',
      'help': 'Help',
      'settings': 'Settings',
      'customers': 'Customers',
      'notifications': 'Notifications',
      'change_language': 'Change Language',
      'smart_invoice': 'Smart Invoice',
      'number': 'Number',
      'not_specified': 'Not specified',
      'items_count': 'Items count',
      'total_weight': 'Total weight',
      'total_expenses': 'Total expenses',
      'goods_total': 'Goods total',
      'select_all': 'Select all',
      'add_new': 'Add new',
      'delete_selected': 'Delete selected',
      'clear_selection': 'Clear selection',
      'supplier_ref': 'Supplier Ref',
      'article': 'Article',
      'quantity': 'Quantity',
      'weight': 'Weight',
      'unit_price': 'Unit price',
      'total_amount': 'Total amount',
      'purchase_price': 'Purchase price',
      'other_expenses': 'Other expenses',
      'item_cost': 'Item cost',
      'actions': 'Actions',
      'edit': 'Edit',
      'delete': 'Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'required': 'Required',
      'invalid_number': 'Invalid number',
      'integer_only': 'Integer only',
      'expense_details': 'Expense details (enter amounts without VAT)',
      'transit': 'Transit',
      'customs': 'Customs',
      'exchange_cheque': 'Exchange Cheque',
      'freight': 'Freight',
      'other': 'Other',
      'exchange_rate': 'Exchange rate',
      'confirm_delete': 'Confirm delete',
      'delete_selected_items': 'Delete selected items?',
      'delete_this_item': 'Delete this item?',
      'enter_value': 'Enter value',
      'clear_value': 'Clear value',
    },
    'fr': {
      'purchases': 'Achats',
      'sales': 'Ventes',
      'inventory': 'Inventaire',
      'production': 'Production',
      'financial_transactions': 'Transactions financières',
      'help': 'Aide',
      'settings': 'Paramètres',
      'customers': 'Clients',
      'notifications': 'Notifications',
      'change_language': 'Changer de langue',
      'smart_invoice': 'Facture intelligente',
      'number': 'Numéro',
      'not_specified': 'Non spécifié',
      'items_count': 'Nombre d’articles',
      'total_weight': 'Poids total',
      'total_expenses': 'Total des dépenses',
      'goods_total': 'Total marchandises',
      'select_all': 'Tout sélectionner',
      'add_new': 'Ajouter',
      'delete_selected': 'Supprimer la sélection',
      'clear_selection': 'Effacer la sélection',
      'supplier_ref': 'Réf. fournisseur',
      'article': 'Article',
      'quantity': 'Quantité',
      'weight': 'Poids',
      'unit_price': 'Prix unitaire',
      'total_amount': 'Montant total',
      'purchase_price': 'Prix d’achat',
      'other_expenses': 'Autres frais',
      'item_cost': 'Coût de l’article',
      'actions': 'Actions',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'required': 'Obligatoire',
      'invalid_number': 'Nombre invalide',
      'integer_only': 'Entier seulement',
      'expense_details': 'Détails des dépenses (saisir les montants hors TVA)',
      'transit': 'Transport',
      'customs': 'Droit de douane',
      'exchange_cheque': 'Chèque de change',
      'freight': 'Fret',
      'other': 'Autre',
      'exchange_rate': 'Taux de change',
      'confirm_delete': 'Confirmer la suppression',
      'delete_selected_items': 'Supprimer les éléments sélectionnés ?',
      'delete_this_item': 'Supprimer cet élément ?',
      'enter_value': 'Entrer la valeur',
      'clear_value': 'Effacer la valeur',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['ar']![key] ?? key;
  }
}
